---
baseurl: "http://localhost"
languageCode: "en-us"
title: "Index Page Title"
Taxonomies:
    tag: "tags"
params:
    GoogleAnalyticsId: "UA-XYSYXYSY-X"
    FullName: "First Last"
    AvatarImage: ""
    BannerImage: "http://placehold.it/500x300"
    Github: ""
    Twitter: ""
    Stackoverflow: ""
    Linkedin: ""
    SiteTitle: "example.com"
---
